name    'mjanser-eclipse'
version '0.2.1'
source 'git://github.com/mjanser/puppet-eclipse.git'
author 'Martin Janser'
license 'MIT'
summary 'Install Eclipse'
description 'Install Eclipse with plugins'
project_page 'https://github.com/mjanser/puppet-eclipse.git'

dependency 'nanliu/archive', '>= 0.3.0'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
